apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kps-kube-prometheus-stack-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'discord'
      group_by: ['alertname']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 12h

    receivers:
    - name: 'discord'
      slack_configs:
      - api_url: '<LINK-WEBHOOK-DISCORD>'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts -}}
          **Status:** {{ .Status }}
          **Instance:** {{ .Labels.instance }}
          **Summary:** {{ .Annotations.summary }}
          {{ end }}
