apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-high
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress-high
  template:
    metadata:
      labels:
        app: cpu-stress-high
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "2000m"
            memory: "256Mi"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "Starting HIGH CPU stress..."
            stress --cpu 4 --timeout 180s --verbose
            echo "Sleeping 5s..."
            sleep 5
          done
