version: "3"

services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
        ports:
            - 9090:9090
    
    alertmanager:
        image: prom/alertmanager
        volumes:
            - ./alertmanager/config.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - 9093:9093
        depends_on:
            - discord-relay
    
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
    
    node-exporter:
        image: prom/node-exporter
        ports:
            - 9100:9100
    
    web:
        build: ./web_app
        ports:
            - 5000:5000
    
    loki:
        image: grafana/loki:2.9.0
        ports:
            - 3100:3100
        command: -config.file=/etc/loki/local-config.yml

    discord-relay:
        image: benjojo/alertmanager-discord
        ports:
            - 9094:9094
        environment:
            - DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/1429790403426779198/t6LfTG6hAvq35AB4turLAXDoXOUvt94NnzXM1lKZN2YsZjRtOPNVFzwHauLMZDAFJosZ